### ISSUE TITLE
Iconv-lite warning: decode()-ing strings is deprecated

### ISSUE THREAD

**Issue by steverandy** [scripting/feedRead#2]
Got the following error when using parseString function.

```
console.error node_modules/iconv-lite/lib/index.js:33
      Iconv-lite warning: decode()-ing strings is deprecated. Refer to https://github.com/ashtuchkin/iconv-lite/wiki/Use-Buffers-when-decoding
```

**Comment by scripting** [comment]
Hi @steverandy -- I just did the following --

1. In the [readfile](https://github.com/scripting/feedRead/blob/master/examples/readfile/read.js) example, I ran the app. It worked.

2. I then did an _npm update_ to see if there was a new version of iconv-lite. There wasn't.

I didn't see the deprecation warning. So either provide steps to reproduce that I can look into, or see what's different about how you're using parseString and how I'm using it, and have a look from there.

**Comment by steverandy** [comment]
@scripting Sorry my mistake passing wrong argument to the parseString function.
